import { ref } from 'vue'

function createInitialPiDocuments() {
  return [
    {
      id: 'PI26001',
      issueDate: '2026/02/01',
      clientName: 'COOLSAY SDN BHD',
      clientAddress: 'Lot 18, Jalan Pelabuhan Utara 27, 42000 Port Klang, Selangor, Malaysia',
      buyerName: 'Mr. Ahmad Razak (Purchasing Manager)',
      currency: 'USD',
      country: '말레이시아',
      itemName: 'Wireless Presenter',
      amount: '$21,870',
      incoterms: 'FOB',
      namedPlace: 'BUSAN',
      manager: '김영업',
      status: '확정',
      deliveryDate: '2026/04/15',
      items: [
        { name: 'Wireless Presenter', qty: '30', unit: 'EA', unitPrice: '55', amount: '1650', remark: '' },
        { name: 'USB-C Hub 7-in-1', qty: '200', unit: 'EA', unitPrice: '48', amount: '9600', remark: '' },
        { name: 'Bluetooth Headset', qty: '100', unit: 'EA', unitPrice: '95', amount: '9500', remark: '' },
        { name: 'Wireless Mouse', qty: '32', unit: 'EA', unitPrice: '35', amount: '1120', remark: '' },
      ],
    },
    {
      id: 'PI26002',
      issueDate: '2026/02/15',
      clientName: 'TechBridge GmbH',
      clientAddress: 'Am Sandtorkai 35, 20457 Hamburg, Germany',
      buyerName: 'Ms. Hanna Schneider (Procurement Lead)',
      currency: 'EUR',
      country: '독일',
      itemName: 'Smart Projector FHD',
      amount: '€60,900',
      incoterms: 'CIF',
      namedPlace: 'HAMBURG',
      manager: '김영업',
      status: '발송',
      deliveryDate: '2026/05/20',
      items: [
        { name: 'Smart Projector FHD', qty: '40', unit: 'EA', unitPrice: '780', amount: '31200', remark: '' },
        { name: 'All-in-One PC 24"', qty: '18', unit: 'EA', unitPrice: '1650', amount: '29700', remark: '' },
      ],
    },
    {
      id: 'PI26003',
      issueDate: '2026/03/01',
      clientName: 'Pacific Trading Inc.',
      clientAddress: '1201 Harbor Avenue SW, Seattle, WA 98134, USA',
      buyerName: 'Mr. Jacob Miller (Import Manager)',
      currency: 'USD',
      country: '미국',
      itemName: 'External SSD 1TB',
      amount: '$14,840',
      incoterms: 'CFR',
      namedPlace: 'LOS ANGELES',
      manager: '정영업',
      status: '초안',
      deliveryDate: '2026/06/01',
      items: [
        { name: 'External SSD 1TB', qty: '80', unit: 'EA', unitPrice: '98', amount: '7840', remark: '' },
        { name: 'Mechanical Keyboard', qty: '40', unit: 'EA', unitPrice: '120', amount: '4800', remark: '' },
        { name: 'Wireless Presenter', qty: '40', unit: 'EA', unitPrice: '55', amount: '2200', remark: '' },
      ],
    },
    {
      id: 'PI26004',
      issueDate: '2025/12/10',
      clientName: 'Viet Steel JSC',
      clientAddress: '12 Nguyen Hue Boulevard, District 1, Ho Chi Minh City, Vietnam',
      buyerName: 'Purchasing Team',
      currency: 'USD',
      country: '베트남',
      itemName: 'H-Beam 482x300x11x15',
      amount: '$53,600',
      incoterms: 'FOB',
      namedPlace: 'BUSAN',
      manager: '정영업',
      status: '확정',
      deliveryDate: '2026/04/30',
      items: [
        { name: 'H-Beam 482x300x11x15', qty: '40', unit: 'EA', unitPrice: '1340', amount: '53600', remark: '' },
      ],
    },
    {
      id: 'PI26005',
      issueDate: '2026/01/15',
      clientName: 'Siam Industrial Co., Ltd.',
      clientAddress: '88 Bangna-Trad Road, Bang Phli, Samut Prakan 10540, Thailand',
      buyerName: 'Purchasing Team',
      currency: 'USD',
      country: '태국',
      itemName: 'H-Beam 488x300x11x18',
      amount: '$38,850',
      incoterms: 'FOB',
      namedPlace: 'BUSAN',
      manager: '김영업',
      status: '확정',
      deliveryDate: '2026/05/15',
      items: [
        { name: 'H-Beam 488x300x11x18', qty: '21', unit: 'EA', unitPrice: '1850', amount: '38850', remark: '' },
      ],
    },
    {
      id: 'PI26006',
      issueDate: '2026/03/05',
      clientName: 'Meridian Engineering Pte Ltd',
      clientAddress: '21 Jurong Port Road, Singapore 619095',
      buyerName: 'Procurement Team',
      currency: 'USD',
      country: '싱가포르',
      itemName: 'Seamless Steel Pipe 168x7',
      amount: '$29,700',
      incoterms: 'FOB',
      namedPlace: 'BUSAN',
      manager: '정영업',
      status: '발송',
      deliveryDate: '2026/06/10',
      items: [
        { name: 'Seamless Steel Pipe 168x7', qty: '90', unit: 'EA', unitPrice: '330', amount: '29700', remark: '' },
      ],
    },
    {
      id: 'PI26007',
      issueDate: '2026/01/20',
      clientName: 'Tata Steel Traders Pvt Ltd',
      clientAddress: '3rd Floor, Commerce House, Nariman Point, Mumbai 400021, India',
      buyerName: 'Procurement Team',
      currency: 'USD',
      country: '인도',
      itemName: 'H-Beam 482x300x11x15',
      amount: '$76,400',
      incoterms: 'FOB',
      namedPlace: 'BUSAN',
      manager: '김영업',
      status: '확정',
      deliveryDate: '2026/05/30',
      items: [
        { name: 'H-Beam 482x300x11x15', qty: '40', unit: 'EA', unitPrice: '1910', amount: '76400', remark: '' },
      ],
    },
    {
      id: 'PI26008',
      issueDate: '2026/03/10',
      clientName: 'OzSteel Supplies Pty Ltd',
      clientAddress: '42 Harbour Street, Sydney NSW 2000, Australia',
      buyerName: 'Procurement Team',
      currency: 'USD',
      country: '호주',
      itemName: 'Hydraulic Cylinder 100x500',
      amount: '$23,960',
      incoterms: 'FOB',
      namedPlace: 'BUSAN',
      manager: '정영업',
      status: '초안',
      deliveryDate: '2026/06/30',
      items: [
        { name: 'Hydraulic Cylinder 100x500', qty: '28', unit: 'EA', unitPrice: '820', amount: '22960', remark: '' },
        { name: 'Gear Pump GP-20', qty: '4', unit: 'EA', unitPrice: '250', amount: '1000', remark: '' },
      ],
    },
  ]
}

const piDocuments = ref(createInitialPiDocuments())

export function usePiDocuments() {
  return piDocuments
}
